tortworth/views/room.py
from flask import Blueprint, redirect, flash, request, render_template, url_for, session
from flask_login import current_user, login_required
from tortworth import db

from tortworth.utils import *
from tortworth.models import UploadedImage, Room, get_model_dict, RoomNote, to_dict
from tortworth.forms import UploadFile, NewNote, EditRoom
from werkzeug import secure_filename

import uuid


mod = Blueprint('room', __name__)

@mod.route('/test')
def homepage():
    return 'You are on the homepage'

@mod.route('/search', methods=['POST','GET'])
def search():
    rooms = Room.query.all()
    if not request.form:
        return render_template('room/search.html', rooms=rooms)
    room = request.form.get('Room')
    room = room.lstrip('0')
    if room == '':
        flash('No room entered.')
        return redirect(url_for('room.search'))
    elif all(x.isalpha() or x.isspace() for x in room):
        flash('Please enter room number, not name.')
        return redirect(url_for('room.search'))
    search = Room.query.get(room)
    if search:
        return redirect('/room/{}'.format(room))
    else:
        flash('Room not found')
        return redirect(url_for('room.search'))

@mod.route('/upload/<room_number>', methods=['GET', 'POST'])
def images(room_number):
    form = UploadFile()
    all_images = UploadedImage.query.filter_by(room=room_number).all()
    length = len(all_images)
    file_paths = []
    for x in all_images:
        file_paths.append(f"/static/uploads/{x.file_name}")
    if length == 0:
        file_paths = False
    if form.validate_on_submit():
        f = request.files.getlist('file')
        for image in f:
            image_file_name = f'{room_number}-' + \
                str(uuid.uuid4()) + secure_filename(image.filename)
            image_file = os.path.join(os.path.abspath('tortworth/static/uploads'), image_file_name)
            image.save(image_file)
            image_upload = UploadedImage(
                room=room_number,
                file_name=image_file_name,
                file_path=image_file
            )
            db.session.add(image_upload)
        db.session.commit()
        db.session.close()
        flash('Images added.')
        return redirect(url_for('room.search'))

    return render_template('room/upload.html', room=room_number, images=all_images, form=form)

@mod.route('/edit/<room_number>')
def edit(room_number):
    room = Room.query.get(room_number)
    form = EditRoom(obj=room)
    return render_template('room/edit.html', form=form)

@mod.route('/test')
def delete():
    pass

@mod.route('/<room_number>')
def room(room_number):
    all_images = UploadedImage.query.filter_by(room=room_number).all()
    file_paths = []
    for x in all_images:
        file_paths.append(f"{x.file_name}")
    if len(all_images) == 0:
        file_paths = False
    room = Room.query.get(room_number)
    notes = RoomNote.query.filter_by(room_id=room_number)
    print(type(notes.count()))
    if notes.count() == 0:
        notes = False
    form = NewNote()
    return render_template('room/room.html', notes=notes, room=room, form=form, images=file_paths)


@mod.route('/note/add/<room_number>', methods=['POST', 'GET'])
def add_note(room_number):
    form = NewNote()
    if form.validate_on_submit():
        new_note = RoomNote(
            body = form.body.data,
            user_id = current_user.id,
            room_id = room_number
        )
        db.session.add(new_note)
        db.session.commit()
        flash('Note added')
        return redirect(url_for('.room', room_number=room_number))
    return render_template('room/add_note.html', form=form, room=room_number)

tortworth/templates/room/edit.html
{% extends "layout.html" %} {% block title %}Search{% endblock %} {% block head %} {{ super() }} {% endblock %} {%block
content%}
<div class="col-8">
<div class="card">
    <div class="card-header">
        Edit Room {{room}}
    </div>
    <div class="card-body">


        <form class="form-group" action="{{ url_for('room.edit', room_number=room) }}" method="post" novalidate>

            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-6">
                    {{form.view.label}}
                    {{form.view(class_="form-control")}}
                </div>
                <div class="col-6">
                    {{form.floor.label}}
                    {{form.floor(class="form-control")}}
                </div>
                <div class="col-6">
                    {{form.size.label}}
                    {{form.size(class="form-control")}}
                </div>
                <div class="col-6">
                    {{form.room_type.label}}
                    {{form.room_type(class_="form-control")}}
                </div>

            </div>
            <div class="row">
                <div class="col-6 p-5 mr-auto">
                    <label class="custom-control custom-checkbox">
                        {{form.desk(class="custom-control-input")}}
                        <span class="custom-control-label">
                            {{form.desk.label}}
                        </span>
                    </label>

                    <label class="custom-control custom-checkbox ">
                        {{form.desk(class="custom-control-input")}}
                        <span class="custom-control-label">
                            {{form.desk.label}}
                        </span>
                    </label>

                    <label class="custom-control custom-checkbox ">
                        {{form.desk(class="custom-control-input")}}
                        <span class="custom-control-label">
                            {{form.desk.label}}
                        </span>
                    </label>
                    <label class="custom-control custom-checkbox ">
                            {{form.desk(class="custom-control-input")}}
                            <span class="custom-control-label">
                                {{form.desk.label}}
                            </span>
                        </label>
                        <label class="custom-control custom-checkbox ">
                                {{form.desk(class="custom-control-input")}}
                                <span class="custom-control-label">
                                    {{form.desk.label}}
                                </span>
                            </label>
           
                        <label class="custom-control custom-checkbox ">
                                {{form.desk(class="custom-control-input")}}
                                <span class="custom-control-label">
                                    {{form.desk.label}}
                                </span>
                            </label>
                            <label class="custom-control custom-checkbox ">
                                    {{form.desk(class="custom-control-input")}}
                                    <span class="custom-control-label">
                                        {{form.desk.label}}
                                    </span>
                                </label>
                                <label class="custom-control custom-checkbox ">
                                        {{form.desk(class="custom-control-input")}}
                                        <span class="custom-control-label">
                                            {{form.desk.label}}
                                        </span>
                                    </label>
                                    <label class="custom-control custom-checkbox ">
                                            {{form.desk(class="custom-control-input")}}
                                            <span class="custom-control-label">
                                                {{form.desk.label}}
                                            </span>
                                        </label>
                                        <label class="custom-control custom-checkbox ">
                                                {{form.desk(class="custom-control-input")}}
                                                <span class="custom-control-label">
                                                    {{form.desk.label}}
                                                </span>
                                            </label>

                </div>
            </div>


        </form>
    </div></div>
</div>
{% endblock %}

tortworth/templates/room/images.html
<h1>{{length}}</h1>
{% for image in images %}
<img src="{{image}}">
{%endfor%}

tortworth/templates/room/room.html
{% extends "layout.html" %}
{% set active_page = "search" %}
{% block title %}Search{% endblock %} {% block head %} {{ super() }} {% endblock %}
{%block content%}
<div class="page-header">
  <div class="page-title">
    Room information
  </div>
</div>
<div class="row">

  <div class="col-12 col-sm-4">
    <div class="card">
      <div class="card-header h1 font-weight-bold p-5">
      <span class="bounce animated">Room {{room.id}}</span> 
        <div class="card-options pt-5 pb-5">
          <a role="button" href="{{ url_for('room.edit', room_number=room.id) }}" class="btn btn-outline-primary btn-sm"> <i class="fe fe-edit"></i> Edit room</a>
        </div>
      </div>
      <!-- <div class="card-footer">
          AKA Teulon
        </div> -->
    </div>
    <div id="newNote" class="collapse">
      <div class="card shadow">
        <div class="card-status card-status-left bg-success"></div>
        <div class="card-header">
          <div class="card-title">New note</div>
        </div>
        <div class="card-body">
          <form class="pb-5" action="{{ url_for('room.add_note', room_number=room.id) }}" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ form.body.label }}
            {{ form.body(class="form-control") }}
            <button type="submit" class="btn btn-primary btn-sm btn-block pull-right mt-3">Submit</button>
          </form>

        </div>
      </div>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {%for cat, msg in messages%}
      <div class="card">
        <div class="card-body text-center">
         <i class="fe fe-thumbs-up"></i> {{msg}}
        </div>
      </div>
      {%endfor%}
      {% endif %}
      {% endwith %}

    <div id="roomNotes" class="card">
      <div class="card-header">
        <div class="card-title">Room notes </div>
        <div class="card-options">
          <a name="" id="" data-toggle="collapse" class="btn btn-outline-primary btn-sm ml-3" href="#newNote" role="button"
            aria-expanded="false" aria-controls="newNote">
            <i class="fe fe-plus"></i>
            Add room note
          </a>
          <a href="#" class="card-options-collapse" data-toggle="card-collapse">
            <i class="fe fe-chevron-up btn btn-outline-primary btn-sm"></i></a>
        </div>
      </div>
      <table class="table card-table">
        <tbody>
          {% if notes %}
          {% for note in notes|reverse%}
          <tr>
            <td width="1"><i class="fe fe-message-square text-muted" aria-hidden="true"></i>
            </td>
            <td>{{note.body}}</td>
            <td class="small text-muted text-right">{{note.room_note_author.nickname}} <i class="fe fe-more-vertical"></i>

            </td>
          </tr>
          {%endfor%}
          {%else%}
          <tr>
            <td>
              There are no notes about this room.
            </td>
          </tr>
          {%endif%}
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-12 col-sm-8">
    <div class="row">
      <div class="col-4">
        <div class="card">
          <div class="card-body text-center">
            <div class="h5">Connecting</div>
            <div class="h2 font-weight-bold mb-4">{%if room.connecting%}Yes{%else%}No{%endif%}</div>
          </div>
        </div>
      </div>

      <div class="col-4">
        <div class="card">
          <div class="card-body text-center">
            <div class="h5">Zip & Link</div>
            <div class="h2 font-weight-bold mb-4">{%if room.zip_link%}Yes{%else%}No{%endif%}</div>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="card">
          <div class="card-body text-center">
            <div class="h5">Sofa bed</div>
            <div class="h2 font-weight-bold mb-4">{%if room.sofa_bed%}Yes{%else%}No{%endif%}</div>
          </div>
        </div>
      </div>
      <div class="col-12">
        <div class="card">
          <div class="card-body text-center">
            <div class="h5">View from room</div>
            <div class="h2 font-weight-bold mb-4">{{room.view}}</div>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          Room Inventory
        </div>
      </div>
      <div class="card-body">
        <div class="row text-center">
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-down text-danger"></i>{% if room.armchair%} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Armchair</div>
          </div>
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-up text-success"></i>{% if room.bathroom_windows %} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Bathroom Windows</div>
          </div>
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-up text-success"></i>{% if room.coffee_table %} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Coffee Table</div>
          </div>
        </div>
        <div class="row text-center mt-5">
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-down text-danger"></i>{% if room.desk%} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Desk</div>
          </div>
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-up text-success"></i>{% if room.fridge %} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Fridge</div>
          </div>
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-up text-success"></i>{% if room.full_mirror %} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Full Length Mirror</div>
          </div>
        </div>
        <div class="row text-center mt-5">
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-down text-danger"></i>{% if room.roll_bath%} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Roll Top Bath</div>
          </div>
          <div class="col-4">
            <h2 class="mb-1"><i class="mdi mdi-trending-up text-success"></i>{% if room.shower_bath %} <i class="fe fe-check text-success"></i>
              {%else%} <i class="fe fe-x text-danger"></i>{%endif%}</h2>
            <div class="text-muted-dark">Shower over bath</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          Room images
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          {% if images %}
          {% for image in images%}
          <a href="{{ url_for( 'static', filename='uploads/' + image ) }}" data-toggle="lightbox" data-gallery="gallery" class="col-md-4">
            <img class="img-fluid rounded" src="{{ url_for( 'static', filename='uploads/' + image ) }}" alt="">
          </a>
          {%endfor%}
          {%else%}
          There are no images.
          {%endif%}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- <div class="page-header">
  <div>
  <div class="page-title">
      Room {{ room.id }}
  </div>
  <div class="page-description">
    {{floor}}
  </div>
</div>
</div>
<div class="row text-center">
    <div class="col-12 col-sm-4">
        <div class="card">
          <div class="card-body">
            <h1>Room {{room.id}}</h3>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-8">
          <div class="card">
            <div class="card-body">
              <h4>{{room.size}}</h3>
                <span class="text-muted">Room Size</span>

            </div>
          </div>
        </div>
        {%if room_name%}
        <div class="col-12 col-sm">
            <div class="card">
              <div class="card-body">
                <h4>{{room.room_name}}</h3>
                  <span class="text-muted">Room Name</span>
  
              </div>
            </div>
          </div>
          {%endif%}
        <div class="col-12 col-sm-6">
            <div class="card">
              <div class="card-body">
                <h4>{{room.view}}</h3>
                  <span class="text-muted">Room View</span>
              </div>
            </div>
          </div>
</div>

<div class="row">
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          Room Notes
        </div>
      </div>
      <table class="table card-table">
        <tbody>
          {% if notes %}
          {% for note in notes %}
          <tr>
            <td>{{note.body}} 
              <div class="float-right">{{note.room_note_author.nickname}} 
              {%if current_user.admin %} <i class="fa fa-trash text-danger" aria-hidden="true"></i>{%endif%}
              
              
            </div></td>
          </tr>
          {%endfor%}
          {%else%}
          <tr>
            <td>There are no notes about this room.</td>
          </tr>
          {%endif%}
        </tbody>
      </table>
      <div class="card-footer">
        <a class="btn btn-outline-primary btn-sm float-right" href="{{ url_for('room.add_note', room_number=room.id) }}" role="button">Add note</a>
      </div>
    </div>
  </div>
</div> -->

{% endblock %}

tortworth/templates/room/search.html
{% extends "layout.html" %}
{% set active_page = "search" %}

{% block title %}Search{% endblock %}
{% block head %} {{ super() }} {% endblock %} {%block content%}
<div class="page-header">
    <h1 class="page-title">
        Room search
    </h1>

</div>
<div class="row">
    <div class="col-12 col-sm-6">
        <div class="card mx-auto">
            <div class="card-body">
                <form class="form-inline" action="{{ url_for('room.search') }}" method="post">

                    <input id="room" placeholder="Room number.." class="form-control mr-5" type="text" name="Room"
                        autocomplete="off" />
                    <button class="btn btn-primary m-2">
                        <input type="button" name="submit" style="display: none;">
                        <i class="fa fa-search"></i> Search
                    </button>

                    <!-- <button class="btn btn-info m-2 form-inline d-none d-sm-block">
                        <input type="button" name="print" style="display: none;">
                        <i class="fa fa-print"></i> Print
                    </button> -->

                </form>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {%for cat, msg in messages%}

                <div class="text-danger font-weight-bold h4 pt-5">
                    <i class="fe fe-alert-triangle"></i> {{ msg }}
                </div>

                {%endfor%}
                {% endif %}
                {% endwith %}
            </div>
        </div>


    </div>

</div>
<div class="row">
    <div class="col-12 col-lg-4">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Interconnecting rooms
                </div>
            </div>
            <table class="table card-table">
                <tbody>
                    {% for room in rooms%}
                    {% if room.connecting %}
                    <tr>
                        <td width="1"><i class="fa fa-bed text-muted" aria-hidden="true"></i>
                        </td>
                        <td>Room {{room.id}}</td>
                    </tr>
                    {%endif%}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 col-lg-8">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Rooms with Sofabeds
                </div>
            </div>
            <div class="card-body pt-0">
                <div class="row">
                    {% for room in rooms %}
                        {% if room.sofa_bed %}
                        <div class="col-4 p-3 border">
                        <a href="{{url_for('room.room', room_number=room.id)}}" class="text-dark">
                        
                           <i class="fa fa-bed text-muted mr-3" aria-hidden="true"></i> Room {{room.id}}
                        </a> 
                        </div>
                    
                        {%endif%}
                    

                    {% endfor %}
                </div>
            </div>

        </div>
    </div>

</div>

{% endblock %}

tortworth/templates/room/upload.html
{% extends "layout.html" %} {% block title %}Upload Image{% endblock %} {% block head %} {{ super() }} {% endblock %} {%
block content%}
<style>
    *:focus {
        outline: none;
    }

    .uploader {
        /* color:white; */
        border: solid 2px black;
    }

    input[type="file" i] {
        color: black;
        padding: 50px;
    }
</style>
<div class="container-fluid bg-dark text-light pb-5">
    <div class="row">

        <div class="col"></div>

        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-6">
            <h1 class="display-4 text-center pt-4">Upload Images</h1>
        </div>
        <div class="col"></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-md-8 col-sm-12 mt-5">
            {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
            <div id="alert" class="alert alert-success w-100 mt-4 mx-auto text-center">
                <strong>{{ message }}</strong>
            </div>
            {% endfor %} {% endif %} {% endwith %}
            <div class="form-group text-center">
                <form action="{{ url_for('room.images', room_number=room )}}" method="POST" enctype="multipart/form-data">
                    {{ form.hidden_tag() }} {{ form.file(class="uploader") }}
                    <br>
                    <br>
                    <input type="submit" class="btn btn-success btn-lg">
                    <a href="{{ url_for('room.room', room_number=room) }}" class="btn btn-primary btn-lg">Go Back</a>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
    <!-- third column -->
    <div class="text-center pt-5">
        <!-- need to finish this -->
        <span class="display-4">Images</span>
    </div>
    <hr>
    <div class="row mb-5">
        {% if images %} {% for image in images %}

        <!-- <div class="col-12 col-sm-12 col-md-6 p-4">
                        <a href="#" class="btn mx-auto btn-danger">Delete</a>  <img src="{{image}}" onerror="this.src='https://www.lifewire.com/thmb/qLv10Pgd30kCy7OxXacwOWKxZ8M=/768x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/shutterstock_325494917-5a68d8403418c600190a3e1f.jpg'"
                  class="img-thumbnail">
                  
                </div> -->
        <div class="col-md-4 col-12">
            <div class="card">
                <img src="/static/uploads/{{image.file_name}}" onerror="this.src='https://www.lifewire.com/thmb/qLv10Pgd30kCy7OxXacwOWKxZ8M=/768x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/shutterstock_325494917-5a68d8403418c600190a3e1f.jpg'"
                    class="card-img-top">
                <div class="card-body">
                    <h6 class="card-title">{{ image.file_name }}</h5>
                    <p>Image ID: {{ image.id}}</p>
                </div>
            </div>
        </div>

            {% endfor %} {% else %}
            <div class="col-12 mb-5 text-center">
                <div class="card">
                    <div class="card-body bg-danger">
                        <h5 class="text-light p-1">There is no images of this room.</h5>
                    </div>
                </div>
            </div>
        
    </div>
    {% endif %} {% endblock %}