tortworth/views/admin.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, jsonify
from flask_login import current_user, login_required

from tortworth.models import Room
from .. import db

from tortworth.models import User
from tortworth.forms import UpdateUser

mod = Blueprint('admin', __name__)

@mod.route('/')
@login_required
def index():
    admin = User.query.get(current_user.id)
    if not admin.admin:
        flash("You can't do that. Soz.")
        return index.home()

    users = User.query.all()
    return render_template('admin/index.html', users=users)

@mod.route('/<room_number>')
def my(room_number):
    rooms = Room.query.get(room_number)
    return (f"{rooms.id}, {rooms.view}")

@mod.route("/update/<user_id>", methods=['GET', 'POST'])
@login_required
def update_user(user_id):
    form = UpdateUser()
    user = User.query.get(user_id)

    if request.method == 'POST' and form.validate():
        user.username = request.form['email']
        user.password = request.form['password']
        user.job_title = request.form['job_title']
        user.nickname = request.form['nickname']
        if request.form.get('admin') == 'y':
            user.admin = 1
        else:
            user.admin = 0
        try:
            db.session.commit()
        except:
            db.session.rollback()
            flash('Email in use already.')
            return index()
        flash(f'{user.username} updated.')
        return index()
    else:
        return render_template('admin_edit.html', form=form, user=user)


@mod.route('/delete_user/<user_id>')
def delete_user(user_id):
    user = User.query.get(user_id)
    db.session.delete(user)
    db.session.commit()
    flash('Deleted {}'.format(user.id))
    return redirect(url_for('.index'))

tortworth/views/log.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required

from tortworth import db
from tortworth.models import Post, PostComment
from tortworth.forms import NewPost, PostCommentForm

import datetime
from datetime import timedelta

mod = Blueprint('log', __name__)

@mod.route('/')
@mod.route('/today')
@login_required
def index():
    posts = Post.query.filter_by(timestamp=datetime.date.today()).all()
    form = PostCommentForm()
    comments = PostComment.query.all()
    return render_template('log/main.html', posts=posts, date=datetime.date.today(), form=form, comments=comments)

@mod.route('/yesterday')
@login_required
def yesterdays_log():
    posts = Post.query.filter_by(
        timestamp=datetime.date.today() - timedelta(days=1)).all()
    form = PostCommentForm()

    return render_template('log/main.html', posts=posts, date=datetime.date.today() - timedelta(days=1), form=form)

@mod.route('/date', methods=['POST', 'GET'])
def pick_log_date():
    if request.form:
        date = request.form['date']
    elif request.args:
        date = request.args.get('date')
    else:
        return 'None'
    dt = datetime.datetime.strptime(str(date), '%Y-%m-%d')
    posts = Post.query.filter_by(timestamp=dt.date()).all()
    form = PostCommentForm()
    return render_template('log/main.html', posts=posts, date=dt.date(), form=form)

@mod.route('/delete/<post_id>')
def delete(post_id):
    post_to_delete = Post.query.get(post_id)
    db.session.delete(post_to_delete)
    db.session.commit()
    return (' ', 204)

@mod.route('/comment/<post_id>', methods=['POST'])
def comment(post_id):
    form = PostCommentForm()
    if form.validate_on_submit():
        new_post = PostComment(
            body = form.body.data,
            user_id = int(current_user.id),
            post = int(post_id)
            )
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('.index'))
    return 'nope'

@mod.route('/create/<date>', methods=['GET', 'POST'])
@login_required
def create(date):
    dt = datetime.datetime.strptime(date, '%Y-%m-%d')
    form = NewPost()
    if form.validate_on_submit():
        new_post = Post(
            body=form.body.data,
            user_id=current_user.id,
            sentiment=form.sentiment.data,
            department=form.department.data,
            guest_name=form.guest_name.data,
            arrival_date=form.arrival_date.data,
            guest_room = form.guest_room.data,
            resolution = form.resolution.data,
            cost = form.cost.data,
            timestamp=dt.date())
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('.pick_log_date', date=dt.date()))

    return render_template('log/posts.html', date=dt.date(), form=form)

tortworth/views/user.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, current_user

from tortworth import db
from tortworth.forms import LoginUser, RegisterUser
from tortworth.models import User, Post
from tortworth.utils import greeting

mod = Blueprint('user', __name__)
@mod.route('/')
def index():
    return 'This is where the ME page would go :)'

@mod.route('/user/<user_id>')
def users_stream(user_id):
    user = User.query.get(user_id)
    posts = Post.query.filter_by(user_id=user.id)
    return render_template('log/posts.html', user=user, posts=posts, form=forms.NewPost())

@mod.route('/profile')
def user_profile():
    user_id = request.args.get('user')
    user = User.query.get(user_id)
    users_posts = Post.query.filter_by(user_id=user_id)
    return render_template(
        'user/posts.html',
        user=user,
        total_posts=users_posts.count(),
        posts=users_posts)

@mod.route('/register', methods=['POST', 'GET'])
def register():
    form = RegisterUser()
    if form.validate_on_submit():
        if form.passcode.data != '1853':
            flash('Passcode is incorrect')
            return redirect(url_for('user.register'))
        new_user = User(
            username = form.email.data,
            password = form.password.data,
            job_title = form.job_title.data,
            nickname = form.nickname.data,
            admin=False
        )
        try:
            db.session.add(new_user)
            db.session.commit()
            flash("Yay! You registered, now login.")
            return redirect(url_for('index.home'))
        except:
            flash('Whoops. I already have that email.')
            return redirect(url_for('user.register'))
        
    return render_template('user/register.html', form=form)

@mod.route("/logout")
def logout():
    """Logout Form"""
    logout_user()
    flash('Successfully logged out.', category='warning')
    return redirect(url_for('index.home'))

@mod.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.home'))
    form = LoginUser()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.email.data.lower()).first()
        if user is not None and user.password == form.password.data:
            login_user(user=user)
            next = request.args.get('next')
            return redirect(next or url_for('index.home'))
        else:
            flash('Username or password are incorrect.', category='error')
            return redirect(url_for('user.login'))
    return render_template('user/login.html', form=form)

tortworth/templates/empty.html
{% extends "layout.html" %}
{% block content%}

<div class="page-header">
    <h1 class="page-title">
        Homepage
    </h1>

</div>
<!-- <div class="alert alert-primary text-center" role="alert">
        <i class="fe fe-info"></i> This is a  way of setting an "announcement".
      </div> -->
<div class="card">
    <div class="card-status card-status-left bg-blue"></div>
    <div class="card-body p-3 "><i class="fe fe-info mr-3"></i>These figures are completely made up.</div>

</div>
<div class="row">
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">178</div>
                <div class="text-muted mb-4">Rooms Sold</div>
            </div>
        </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">318</div>
                <div class="text-muted mb-4">Sleepers</div>
            </div>
        </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">88%</div>
                <div class="text-muted mb-4">Occupancy</div>
            </div>
        </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">£190</div>
                <div class="text-muted mb-4">Best Available Rate</div>
            </div>
        </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">147</div>
                <div class="text-muted mb-4">Arrivals</div>
            </div>
        </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-2">
        <div class="card">
            <div class="card-body p-5 text-center">
                <div class="h1 m-0 mt-4">59</div>
                <div class="text-muted mb-4">Departures</div>
            </div>
        </div>
    </div>
</div>
<div class="row row-cards">
    <div class="col-12 col-sm-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Duty Managers</div>
            </div>
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-4"><i class="fe fe-sun"></i>
                        <h4>Early </h1>Sean
                    </div>
                    <div class="col-4"><i class="fe fe-clock"></i>
                        <h4>Late </h4> Sean
                    </div>
                    <div class="col-4"><i class="fe fe-moon"></i>
                        <h4>Night </h4> Sean
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Question of the day!</div>
            </div>
            <div class="card-body">
                Random question here?
                <a data-toggle="collapse" href="#QuestionAnswer" aria-expanded="false" aria-controls="QuestionAnswer"
                    class="float-right">Reveal answer</a>
            </div>
            <div id="QuestionAnswer" class="card-footer collapse">Random answer here</div>
        </div>
    </div>
</div>
<div class="row row-cards">

    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Meetings and Events</div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Room</th>
                                <th scope="col">Organiser</th>
                                <th scope="col">PAX</th>
                                <th scope="col">Start</th>
                                <th scope="col">Finish</th>
                                <th scope="col">Lunch</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Internal</td>
                                <td>Victoria</td>
                                <td>Sean Thorne</td>
                                <td>10</td>
                                <td>10:00</td>
                                <td>16:00</td>
                                <td>12:00</td>
                            </tr>
                            <tr>
                                <td>Internal</td>
                                <td>Victoria</td>
                                <td>Sean Thorne</td>
                                <td>10</td>
                                <td>10:00</td>
                                <td>16:00</td>
                                <td>12:00</td>
                            </tr>
                            <tr>
                                <td>Internal</td>
                                <td>Victoria</td>
                                <td>Sean Thorne</td>
                                <td>10</td>
                                <td>10:00</td>
                                <td>16:00</td>
                                <td>12:00</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Memorable Arrivals</div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Guest Name</th>
                                <th scope="col">Guest Notes</th>
                                <th scope="col">VIP #</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Mark Gruffalo</td>
                                <td>Previous complaint, ref: Sean</td>
                                <td>VIP13</td>
                            </tr>
                            <tr>
                                <td>Mark Gruffalo</td>
                                <td>Previous complaint, ref: Sean</td>
                                <td>VIP13</td>
                            </tr>
                            <tr>
                                <td>Mark Gruffalo</td>
                                <td>Previous complaint, ref: Sean</td>
                                <td>VIP13</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tortworth/templates/landing.html
{% extends "layout.html" %} {% block content%}
<div class="container-fluid bg-dark p-5" style="height: 100vh;">
    <div class="row">
        <div class="col"></div>
        <div class="col-md-6 col-xs-12 col-sm-12 col-lg-4 text-center">
            <h1 class="display-3 pb-4 text-center text-light pt-4">Password recovery</h1>
            <div class="text-center">
                    {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
                    <div class="alert alert-danger text-center" role="alert">
                        <strong>{{ message }}</strong>
                    </div>
                    {% endfor %} {% endif %} {% endwith %}
                <a href="{{url_for('home')}}" class="btn btn-secondary btn-lg btn-block mx-auto">Login</a>
                </form>

            </div>
        </div>
        <div class="col"></div>
    </div>
   
</div>
</div>
{% endblock %}

tortworth/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% set active_page = active_page|default('index') %}

<head>
    {% include 'meta.html' %}
</head>

<body>
    <div class="page ">
        <div class="page-main">
            <div class="header py-4 ">
                <div class="container ">
                    <div class="d-flex ">
                        <a class="header-brand text-uppercase " href="{{url_for('index.home')}}">
                            tortworth portal
                        </a>
                        <div class="d-flex order-lg-2 ml-auto ">
                            <div class="dropdown d-flex">
                                <a class="nav-link icon pr-0" data-toggle="dropdown">
                                    <i class="fe fe-user h2 m-0 "></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow ">
                                    <a href="#" class="dropdown-item d-flex">
                                        <div>
                                            <div class=" text-muted">My Profile</div>
                                        </div>
                                    </a>
                                    <a href="{{url_for('user.logout')}}" class="dropdown-item d-flex">
                                        <div>
                                            <div class="text-muted">
                                                Logout
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <a href="#" class="nav-link pl-0 leading-none d-none d-md-flex " data-toggle="dropdown">
                                    <span class="ml-2">
                                        <span class="text-default">{{current_user.nickname}}</span>
                                        <small class="text-muted d-block mt-1">{{current_user.job_title}}</small>
                                    </span>
                                </a>
                            </div>
                        </div>
                        <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                            <span class="header-toggler-icon"></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="header collapse d-lg-flex p-0 " id="headerMenuCollapse">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 ml-auto">
                            <form action="{{ url_for('room.search') }}" method="post" class="input-icon my-3 my-lg-0">
                                <input name="Room" id="room" type="search" class="form-control header-search"
                                    placeholder="Room Search&hellip;" tabindex="1">
                                <div class="input-icon-addon">
                                    <i class="fe fe-search"></i>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg order-lg-first">
                            <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                                <li class="nav-item">
                                    <a href="{{url_for('index.home')}}" class="nav-link {{ 'active' if active_page == 'index' else '' }}"><i
                                            class="fe fe-home"></i>
                                        Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{url_for('room.search')}}" class="nav-link {{ 'active' if active_page == 'search' else '' }}"><i
                                            class="fe fe-box"></i>
                                        Room Search</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a id="log" href="javascript:void(0)" class="nav-link {{ 'active' if active_page == 'log' else '' }}"
                                        data-toggle="dropdown"><i class="fe fe-calendar"></i>
                                        Guest Log</a>
                                    <div class="dropdown-menu dropdown-menu-arrow">
                                        <a href="{{url_for('log.index')}}" class="dropdown-item ">Today's log</a>
                                        <a href="{{url_for('log.yesterdays_log')}}" class="dropdown-item ">Yesterday's
                                            Log</a>
                                        <a href="{{url_for('log.create', date=date)}}" class="dropdown-item ">Create
                                            Entry Today</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a href="javascript:void(0)" class="nav-link {{ 'active' if active_page == 'information' else '' }}"
                                        data-toggle="dropdown"><i class="fe fe-file"></i>
                                        Information</a>
                                    <div class="dropdown-menu dropdown-menu-arrow">
                                        <a href="./profile.html" class="dropdown-item ">Profile</a>
                                    </div>
                                </li>
                                {% if current_user.admin %}
                                <li class="nav-item dropdown">
                                    <a href="{{url_for('admin.index')}}" class="nav-link {{ 'active' if active_page == 'admin' else '' }}"><i
                                            class="fe fe-users"></i>
                                        Admin</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="my-3 my-md-5">
                <div class="container">
                    {%block content%}
                    {%endblock%}
                </div>

            </div>
        </div>
        <footer class="footer">

            <div class="container">
                <div class="row align-items-center flex-row-reverse">
                    <div class="col-12 col-lg-auto mt-lg-0 text-center">
                        Made with <i class="fe fe-heart"></i> by Sean
                    </div>
                </div>
            </div>
        </footer>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })</script>
    <script src="{{url_for('static', filename='js/custom.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.2.0/ekko-lightbox.min.js"></script>
    <script>
        $(document).on("click", '[data-toggle="lightbox"]', function (event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });</script>
</body>

</html>

tortworth/templates/layoutOUT.html
    <!-- {% include 'header/loader.html' %} -->
    <!-- {% include 'nav/navbar.html' %} -->
    <!-- <main class="page-content h-100 swipe-area" style="background-color:#f0f3f6"> -->
        <!-- {% include 'nav/modal.html' %} -->

tortworth/templates/meta.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta http-equiv="Content-Language" content="en" />
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="theme-color" content="#4188c9">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<link rel="icon" href="./favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"

    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.2.0/ekko-lightbox.min.css">
<!-- Dashboard Core -->
<link href="{{url_for('static', filename='css/dashboard.css')}}" rel="stylesheet" />
<script src="{{url_for('static', filename='js/dashboard.js')}}"></script>

<!-- Input Mask Plugin -->
<script src="{{url_for('static', filename='plugins/input-mask/plugin.js')}}"></script>

<link rel="stylesheet" href="{{url_for('static', filename='css/animate.css')}}">

tortworth/templates/posts.html
{% extends "layout.html" %} {% block title %}Create a new entry{% endblock %} {% block head %} {{ super() }} {%endblock
%} {% block content%}
<div class="container text-center">
    <h1 class="d-none d-sm-block display-4">{{date.strftime('%A %d %B %Y') }}</h1>
    <h1 class="d-block d-sm-none h3">{{date.strftime('%A %d %B %Y') }}</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-10 mx-auto card p-4">


            <h5>Create entry
                <hr>
            </h6>




            <div class="form-group p-2">
                <form action="{{url_for('stream', date=date)}}" method="POST">
                    {{ form.hidden_tag() }}

                    <div class="row">
                        <div class="col-12 col-sm-4 ">
                            {{form.department.label}}
                            {{form.department(id="entryDepartment", class_="form-control", data_toggle="tooltip",
                            data_placement="right",
                            title="The department the entry is about, not yours")}}
                        </div>
                        <div class="col-12 col-sm-4">
                            {{form.sentiment.label}}
                            {{ form.sentiment(id="entrySentiment", class_="form-control" ,data_toggle="tooltip",
                            data_placement="right",
                            title="Does this entry have a positive, negative or neutral sentiment?") }}

                        </div>
                        <div class="col-12 col-sm-4 d-flex align-items-end">
                            <span class="btn btn-block btn-outline-success" data-toggle="collapse" data-target="#addGuestDiv"><i
                                    class="far fa-address-card"></i> Add Guest</span>
                        </div>
                    </div>



           
            <div class="collapse" id="addGuestDiv">
                <div class="row mb-2">
                    <div class="col-6">
                        {{form.guest_name.label}}
                        {{ form.guest_name(id="guestName", class_="form-control") }}
                    </div>
                    <div class="col-6">
                        {{form.arrival_date.label}}
                        {{form.arrival_date(id="entryArrivalDate", class_="form-control datepicker")}}

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12 mb-2">
                    <div class="text-left mt-2 mb-2">
                        <!-- <div class="btn btn-outline-success" data-toggle="collapse" data-target="#addGuestDiv"><i class="far fa-address-card"></i> Add Guest</div> -->
                    </div>


                    {{form.body(id="logBody", class_="form-control", placeholder="Enter your log here...")}}

                </div>

                {% if form.errors %}
                {% for error in form.errors%}
                <div class="alert alert-danger w-100 mt-1 mx-auto">
                    <i class="far fa-times-circle"></i>
                    {{error}}
                </div>
                {% endfor %}
                {% endif %}
                <div class="col-12 mx-auto text-center">
                    {{form.submit(class_="btn btn-lg btn-success shadow")}}
                </div>
            </div>
        </div>
    </div>

</div>

<div class="row mt-2">
    <div class="col-12 col-sm-10 mx-auto card p-3 ">
        <h6>Entry Preview</h6>
        <hr>
        <div class="row">
            <div class="col-12">
                <div id="Entry" class="card shadow border-warning">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <p id="entryBody" class="card-text"></p>
                            </div>
                            <div class="col-12 col-sm-5 border-left">

                                <span id="guestProfile" class="d-none">
                                    Guest name:
                                    <span id="guestNameEntry" class="font-weight-bold"></span>
                                    <br>

                                    Guest arrived:
                                    <strong id="arrivalDate"></strong>
                                </span>

                            </div>






                        </div>

                    </div>
                    <div class="card-footer small" id="cardFooter">

                        <span class="float-left float-sm-right">
                            <span id="footerDepartment">Restaurant</span> |
                            <span id="footerSentiment" class="text-warning font-weight-bold">Neutral</span>
                            |
                            <span id="author">{{current_user.nickname}}</span> |
                            <span id="date">{{date.strftime('%d-%m-%Y')}}</span>
                        </span><br>

                    </div>


                </div>
            </div>

            </form>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
{%endblock%}